version: '3.7'
services:
  # task-allocator-service:
  #   container_name: task-allocator-service
  #   image: task-allocator-service:latest
  #   ports:
  #     - 127.0.0.1:50052:50052
  rabbitmq:
    container_name: rabbitmq
    image: 'bitnami/rabbitmq:latest'
    environment:
    - RABBITMQ_USERNAME=test
    - RABBITMQ_PASSWORD=test
    ports:
      - 127.0.0.1:5672:5672
  handler-service:
    # container_name: handler-service
    deploy:
      replicas: 2
    image: vp-cap/handler-service:latest
    depends_on:
      - rabbitmq
    # ports:
      # - 127.0.0.1:50054:50054
  video-service:
    container_name: video-service
    image: vp-cap/video-service:latest
    ports:
      - 127.0.0.1:50053:50053
  upload-service:
    container_name: upload-service
    image: vp-cap/upload-service:latest
    ports:
      - 127.0.0.1:50051:50051
    depends_on:
      - rabbitmq

networks: 
  default: 
    external: 
      name: common